server.port=${PORT:8080}
spring.application.name=AnimeSense Bot

spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:44809/railway
spring.datasource.username=root
spring.datasource.password=hOUlGnHWFYTqqsPnoXCeKveuIkiOAFyu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.token=8249305108:AAESQz2poeoqLuRB8-HFOjekNYtSWXoWBxI
telegram.bot.username=LazyIsGayBot

admin.username=Aadi
admin.password=Aadiop123
admin.telegram.ids=8447673079

jikan.api.base-url=https://api.jikan.moe/v4
jikan.api.rate-limit-ms=3000

recommendation.max-per-session=5
recommendation.min-rating=6.0
recommendation.genre-weight-increment=0.1
recommendation.genre-weight-decrement=0.05

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
